name: 'AWS Cloudfront Invalidation Sample'

on:
  push:
    branches:
      - 'main'

jobs:
  sample:
    name: sample
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Request Invalidation to AWS Cloudfront
        uses: oneyedev/aws-cloudfront-invalidation@main
        with:
          distribution-id: ${{ secrets.DISTRIBUTION_ID }}
          paths: |
            images*
            sounds/drum.mp3
